version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: mogly_backend
    environment:
      - APP_NAME=MOGLY
      - APP_ENV=production
      - APP_KEY=${APP_KEY} 
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST} 
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE} 
      - DB_USERNAME=${DB_USERNAME} 
      - DB_PASSWORD=${DB_PASSWORD} 
      - CACHE_DRIVER=redis
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: always

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: mogly_front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/etc/share/nginx/html
    depends_on:
      - app
    restart: always

  db:
    image: mariadb:10.6
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Defina no .env
      MYSQL_DATABASE: ${DB_DATABASE} # Defina no .env
      MYSQL_USER: ${DB_USERNAME} # Defina no .env
      MYSQL_PASSWORD: ${DB_PASSWORD} # Defina no .env
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  db_data: