services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mogly_backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000" #(opcional)
    environment:
      - APP_DEBUG=true
      - APP_ENV=local
      - APP_KEY=base64:7IjW8yNDGZV+OP6FIPMJJTon7TfGvJ6/apjxO/TFMJw=
      - DB_CONNECTION=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mogly_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - CACHE_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_CLIENT=redis
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
    command:
      bash -c "php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - db
      - redis

  web:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev 
    container_name: mogly_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000" 
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true # Para resolver problemas de hot-reloading
      - VITE_HOST_API=http://localhost/api
    depends_on:
      - web

  db:
    image: mariadb:10.6
    container_name: mariadb
    volumes:
      - ./data_base:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mogly_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"